#!/usr/bin/env ruby
require 'mkmf'
system( "ln -sf ../mlt.i" )
mltxx_cflags = `pkg-config mlt++-7 --cflags`.strip
system( "swig -c++ -ruby -I../../melted++ #{mltxx_cflags} mlt.i" )
$CPPFLAGS += " -I../.. -I../../melted++ #{mltxx_cflags}"
$LDFLAGS += " -L../../melted++ -lmelted++"
create_makefile('mlt')
system( 'make' )
